<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>gridtag</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../XiPHiAS.GridTag.Core/XiPHiAS.GridTag.Core.csproj" />
    <ProjectReference Include="../XiPHiAS.GridTag.Vision/XiPHiAS.GridTag.Vision.csproj" />
  </ItemGroup>
</Project>
